name: cd

on:
  push:
    branches:
      - main

jobs:
  deploy-github-pages:
    name: Deploy with gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v2

      - name: install dependencies
        run: npm install

      - name: generate build folder
        run: npm run build

      - name: deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
